"""empty message

Revision ID: 0c181da285e2
Revises: 5943ba88f935
Create Date: 2019-12-18 08:43:33.449914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c181da285e2'
down_revision = '5943ba88f935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_hash'), 'login', ['hash'], unique=False)
    op.create_index(op.f('ix_login_status'), 'login', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_status'), table_name='login')
    op.drop_index(op.f('ix_login_hash'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###
