"""empty message

Revision ID: 3e64b09dfc26
Revises: 0c181da285e2
Create Date: 2019-12-18 08:58:59.263696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e64b09dfc26'
down_revision = '0c181da285e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('id_request', sa.Integer(), nullable=False))
    op.drop_constraint('request_status_ibfk_1', 'request_status', type_='foreignkey')
    op.create_foreign_key(None, 'request_status', 'request', ['id_request'], ['id'])
    op.drop_column('request_status', 'id_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('id_activity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'request_status', type_='foreignkey')
    op.create_foreign_key('request_status_ibfk_1', 'request_status', 'request', ['id_activity'], ['id'])
    op.drop_column('request_status', 'id_request')
    # ### end Alembic commands ###
