"""empty message

Revision ID: 5943ba88f935
Revises: 
Create Date: 2019-12-18 08:21:29.948561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5943ba88f935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=16), nullable=False),
    sa.Column('aju', sa.String(length=32), nullable=False),
    sa.Column('perusahaan', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_aju'), 'request', ['aju'], unique=False)
    op.create_index(op.f('ix_request_app'), 'request', ['app'], unique=False)
    op.create_index(op.f('ix_request_perusahaan'), 'request', ['perusahaan'], unique=False)
    op.create_table('request_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_status_status'), 'request_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_status'), table_name='request_status')
    op.drop_table('request_status')
    op.drop_index(op.f('ix_request_perusahaan'), table_name='request')
    op.drop_index(op.f('ix_request_app'), table_name='request')
    op.drop_index(op.f('ix_request_aju'), table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
