"""empty message

Revision ID: b72cad3327fa
Revises: 3e64b09dfc26
Create Date: 2019-12-18 09:37:45.866875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b72cad3327fa'
down_revision = '3e64b09dfc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('loghash', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_login_loghash'), 'login', ['loghash'], unique=False)
    op.drop_index('ix_login_hash', table_name='login')
    op.drop_column('login', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('hash', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_login_hash', 'login', ['hash'], unique=False)
    op.drop_index(op.f('ix_login_loghash'), table_name='login')
    op.drop_column('login', 'loghash')
    # ### end Alembic commands ###
