"""empty message

Revision ID: c46896708280
Revises: 
Create Date: 2020-07-25 10:33:10.514248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46896708280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_hash'), 'log', ['hash'], unique=False)
    op.create_index(op.f('ix_log_status'), 'log', ['status'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=16), nullable=False),
    sa.Column('aju', sa.String(length=32), nullable=False),
    sa.Column('perusahaan', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_aju'), 'request', ['aju'], unique=False)
    op.create_index(op.f('ix_request_app'), 'request', ['app'], unique=False)
    op.create_index(op.f('ix_request_perusahaan'), 'request', ['perusahaan'], unique=False)
    op.create_table('request_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_request', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_request'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_status_status'), 'request_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_status'), table_name='request_status')
    op.drop_table('request_status')
    op.drop_index(op.f('ix_request_perusahaan'), table_name='request')
    op.drop_index(op.f('ix_request_app'), table_name='request')
    op.drop_index(op.f('ix_request_aju'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_log_status'), table_name='log')
    op.drop_index(op.f('ix_log_hash'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
